2019-10-09 21:50:09,083 ERROR: Exception on /index [GET] [in /home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/meth/dev-practice/py-practice/microblog/app/routes.py", line 36, in index
    prev_url=prev_url)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/meth/dev-practice/py-practice/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/meth/dev-practice/py-practice/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/meth/dev-practice/py-practice/microblog/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/meth/dev-practice/py-practice/microblog/app/templates/index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "/home/meth/dev-practice/py-practice/microblog/app/templates/_post.html", line 12, in top-level template code
    said {{ moment(post.timesetamp).fromNow() }}:
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask_moment.py", line 133, in fromNow
    return self._render("fromNow(%s)" % int(no_suffix), refresh)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask_moment.py", line 123, in _render
    t = self._timestamp_as_iso_8601(self.timestamp)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask_moment.py", line 120, in _timestamp_as_iso_8601
    return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
jinja2.exceptions.UndefinedError: 'app.models.Post object' has no attribute 'timesetamp'
2019-10-09 21:50:10,445 ERROR: Exception on /explore [GET] [in /home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/meth/dev-practice/py-practice/microblog/app/routes.py", line 144, in explore
    next_url=next_url, prev_url=prev_url)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/meth/dev-practice/py-practice/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/meth/dev-practice/py-practice/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/meth/dev-practice/py-practice/microblog/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/meth/dev-practice/py-practice/microblog/app/templates/index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "/home/meth/dev-practice/py-practice/microblog/app/templates/_post.html", line 12, in top-level template code
    said {{ moment(post.timesetamp).fromNow() }}:
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask_moment.py", line 133, in fromNow
    return self._render("fromNow(%s)" % int(no_suffix), refresh)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask_moment.py", line 123, in _render
    t = self._timestamp_as_iso_8601(self.timestamp)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask_moment.py", line 120, in _timestamp_as_iso_8601
    return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
jinja2.exceptions.UndefinedError: 'app.models.Post object' has no attribute 'timesetamp'
