2019-10-03 17:40:10,199 ERROR: Exception on /index [GET] [in /home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/meth/dev-practice/py-practice/microblog/app/routes.py", line 27, in index
    return render_template('index.html', title="Sup!", form=form, posts=posts)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/meth/dev-practice/py-practice/microblog/app/templates/index.html", line 16, in template
    {% endif %}
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 213, in parse_if
    'name:endif'))
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 199, in parse_for
    body = self.parse_statements(('name:endfor', 'name:else'))
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
2019-10-03 17:46:35,494 INFO: Microblog startup [in /home/meth/dev-practice/py-practice/microblog/app/__init__.py:42]
2019-10-03 17:49:52,548 INFO: Microblog startup [in /home/meth/dev-practice/py-practice/microblog/app/__init__.py:42]
2019-10-03 17:50:07,660 ERROR: Exception on /index [POST] [in /home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/meth/dev-practice/py-practice/microblog/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/meth/dev-practice/py-practice/microblog/app/routes.py", line 23, in index
    db.commit()
AttributeError: 'SQLAlchemy' object has no attribute 'commit'
2019-10-03 17:50:47,175 INFO: Microblog startup [in /home/meth/dev-practice/py-practice/microblog/app/__init__.py:42]
2019-10-03 17:55:59,847 INFO: Microblog startup [in /home/meth/dev-practice/py-practice/microblog/app/__init__.py:42]
2019-10-03 18:05:45,078 INFO: Microblog startup [in /home/meth/dev-practice/py-practice/microblog/app/__init__.py:42]
2019-10-03 18:19:43,511 INFO: Microblog startup [in /home/meth/dev-practice/py-practice/microblog/app/__init__.py:42]
